apiVersion: batch/v1
kind: CronJob
metadata:
  name: pubg-scrapper
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pubg-scrapper
              image: pubg-scrapper:latest
              imagePullPolicy: Never

          restartPolicy: Never
