spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pubg
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: manual

  data:
    redis:
      host: redis
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.data.redis: DEBUG


